### ISSUE TITLE
Missing operators/keywords such as "not"

### ISSUE THREAD

**Issue by Codingale** [Lixquid/language-gmod-lua#10]
Keywords such as `and` and `not` are not highlighted, along with comparators such as `==`, `~=` and `!=`.

![plvuaij 1](https://cloud.githubusercontent.com/assets/6324853/16671344/eab35b22-446c-11e6-9820-ef37d9f1ee7d.png)

**Comment by Codingale** [comment]
Literally after posting this I noticed, that on the example post for this, it shows an assignment operator (`=`) properly highlighted in orange, yet I don't see it done.

Is there, something I'm missing? Can be be a conflict? Here's a screenshot of my plugins:
![Screenshot](https://cloud.githubusercontent.com/assets/6324853/16671468/814a7c14-446d-11e6-8e09-7d73f462e1bd.png)
I doubt it's a conflict as I disabled them.

**Comment by Lixquid** [comment]
This is because your syntax theme does not support highlighting of operators.

Atom's highlighting is broken up into two areas: The Language or Grammar file, and the Syntax Theme. The Grammar File specifies what a sequence of characters means (For Example: `5` has the meaning `constant.numeric.lua`), and the Syntax Theme attaches colours to these meanings (For Example, `constant.numeric` should be orange).

language-gmod-lua supplies semantic meaning to operators, but your theme has no specified rules for highlighting operators. You can supplement this in your personal stylesheet by adding this to `styles.less`:

``` less
atom-text-editor::shadow .keyword.operator {
    color: #a86;
}
```

**Comment by Codingale** [comment]
Thanks, I'm very new to using Atom I was using Notepad++ mainly before this and I thought I'd give it a try.
